=== metxabe25-ship-it/Markatze-2526/XML/DTD eta XSD/XSD/filmak.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="filmak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="filma" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="izenburua" type="xs:string"/>
                            <xs:element name="zuzendaria" type="xs:string"/>
                            <xs:element name="urtea" type="xs:gYear"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== metxabe25-ship-it/Markatze-2526/XML/DTD eta XSD/XSD/filmak.xml
<?xml version="1.0" encoding="UTF-8"?>
<filmak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="filmak.xsd">
    <filma id="1">
        <izenburua>Inception</izenburua>
        <zuzendaria>Christopher Nolan</zuzendaria>
        <urtea>2010</urtea>
    </filma>
    <filma id="2">
        <izenburua>Spirited Away</izenburua>
        <zuzendaria>Hayao Miyazaki</zuzendaria>
        <urtea>2001</urtea>
    </filma>
</filmak>
